grails-app/domain/edu/chip/i2b2ssr/admin/data/Status.groovy
package edu.chip.i2b2ssr.admin.data

/**
 * @author David Ortiz
 * @date 10/18/12
 * @link http://cbmi.med.harvard.edu
 * @link http://chip.org
 *       <p/>
 *       NOTICE: This software comes with NO guarantees whatsoever and is
 *       licensed as Lgpl Open Source
 * @link http://www.gnu.org/licenses/lgpl.html
 */

class Status implements Comparable<Status> {
  Machine machine
  Date timeStamp = new Date()
  Long numberOfPatients
  Long responseTimeInMillis

  static belongsTo = [Machine]



  static constraints = {

  }

  public int compareTo(Status other) {
      return timeStamp <=> other?.timeStamp // <=> is the compareTo operator in groovy
  }


}

grails-app/controllers/edu/chip/i2b2ssr/admin/StatusController.groovy
package edu.chip.i2b2ssr.admin

import edu.chip.i2b2ssr.admin.data.Machine

/**
 * @author David Ortiz
 * @date 8/27/12
 * @link http://cbmi.med.harvard.edu
 * @link http://chip.org
 *       <p/>
 *       NOTICE: This software comes with NO guarantees whatsoever and is
 *       licensed as Lgpl Open Source
 * @link http://www.gnu.org/licenses/lgpl.html
 */

class StatusController {
  String menuName = "Cluster Status"


  def index = {
    params.max = Math.min(params.max ? params.int('max') : 20, 100)
    params.sort = "endpointStatus"
    params.order = "desc"


    [machines: Machine.list(params),
     count: Machine.count()]

  }


}

grails-app/views/status/index.gsp
<%@ page import="grails.converters.JSON" %>

<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>I2B2SSR Administration</title>
</head>

<body>
<legend>Status of entire network</legend>

<div class="contentPane">

    <table id="userTable" class="table table-striped">
        <!-- Table header -->
        <thead>
        <th>Name</th>
        <th>Status</th>
        <th>Response History</th>
        <th>Patient Count History</th>
        </thead>


        <!-- Table body -->
        <tbody>
        <g:each var="it" in="${machines}" status="i">
            <tr id="machine-${it.id}" class="${(i % 2 == 0) ? 'even' : 'odd'}">
                <td><g:link controller="machine" action="edit" id="${it.id}">${it.name}</g:link></td>
                <td>${it.endpointStatus}</td>
                <td class="graph" data-values="${it.statuses*.responseTimeInMillis as JSON}">
                    <div class="label"/>
                    <div class="chart"/>
                </td>
                <td class="graph" data-values="${it.statuses*.numberOfPatients as JSON}">
                    <div class="label"/>
                    <div class="chart"/>
                </td>
            </tr>
        </g:each>
        </tbody>

    </table>
    <g:paginate controller="status" action="index"
                total="${count}" max="10"/>

</div>
</body>